[package]
name = "kiama"
version = "0.0.0"
edition = "2021"
rust-version = "1.77.0"
description = "Dataframe helper"
documentation = "https://github.com/kiama-rs/kiama/blob/main/README.md"
homepage = "https://github.com/kiama-rs/kiama"
repository = "https://github.com/fossair/kiama"
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
keywords = ["macro"]
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
